import AsyncStorage from '@react-native-async-storage/async-storage';

import { view } from './storybook.requires';

// `storybook.requires.ts` is generated by Metro (`withStorybook` in metro.config.js) from
// `main.ts`; regenerate by hand with `pnpm storybook:generate`.
const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
