// Expo's ambient types (CSS and asset imports, `process.env.EXPO_PUBLIC_*`), committed so
// `tsc` works on a fresh checkout (CI). `expo-env.d.ts` says the same but is generated by
// `expo start` and git-ignored.
/// <reference types="expo/types" />
